# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGAProject/dicom_qpsk/dicom_qpsk.srcs/sources_1/ip/async_fifo_8b/async_fifo_8b.xci
# IP: The module: 'async_fifo_8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGAProject/dicom_qpsk/dicom_qpsk.gen/sources_1/ip/async_fifo_8b/async_fifo_8b.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_8b'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGAProject/dicom_qpsk/dicom_qpsk.gen/sources_1/ip/async_fifo_8b/async_fifo_8b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGAProject/dicom_qpsk/dicom_qpsk.gen/sources_1/ip/async_fifo_8b/async_fifo_8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/FPGAProject/dicom_qpsk/dicom_qpsk.srcs/sources_1/ip/async_fifo_8b/async_fifo_8b.xci
# IP: The module: 'async_fifo_8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGAProject/dicom_qpsk/dicom_qpsk.gen/sources_1/ip/async_fifo_8b/async_fifo_8b.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGAProject/dicom_qpsk/dicom_qpsk.gen/sources_1/ip/async_fifo_8b/async_fifo_8b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FPGAProject/dicom_qpsk/dicom_qpsk.gen/sources_1/ip/async_fifo_8b/async_fifo_8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
